### ISSUE TITLE
Update About Sections In The Repo

### ISSUE THREAD

**Issue by Ankitapradhan04** [LaayaK/LaayakApp#2]
Suggested to update the about section with the following:
- Adding a small description of the project.
- Adding relevant tags related to the project.
 
![12](https://user-images.githubusercontent.com/67707036/141288233-0f12219a-cdd7-48d6-ba65-8cee0644d85a.png)

**Comment by HimeshNayak** [comment]
Thank you @Ankitapradhan04 for pointing that out. Will surely add the description and the tags.
